targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/swaggers/"
          output_folder: "lib/generated_code/"
          input_urls:
            - "https://raw.githubusercontent.com/jacksoncwp/swagger-demo-flutter/main/swagger_demo/swaggers/auth_api.json"
          separate_models: true